/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kube-ci/engine/apis/extension/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeTriggers implements TriggerInterface
type FakeTriggers struct {
	Fake *FakeExtensionV1alpha1
	ns   string
}

var triggersResource = schema.GroupVersionResource{Group: "extension.kube.ci", Version: "v1alpha1", Resource: "triggers"}

var triggersKind = schema.GroupVersionKind{Group: "extension.kube.ci", Version: "v1alpha1", Kind: "Trigger"}

// Create takes the representation of a trigger and creates it.  Returns the server's representation of the trigger, and an error, if there is any.
func (c *FakeTriggers) Create(trigger *v1alpha1.Trigger) (result *v1alpha1.Trigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(triggersResource, c.ns, trigger), &v1alpha1.Trigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Trigger), err
}
