/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	engine_v1alpha1 "kube.ci/engine/apis/engine/v1alpha1"
	versioned "kube.ci/engine/client/clientset/versioned"
	internalinterfaces "kube.ci/engine/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kube.ci/engine/client/listers/engine/v1alpha1"
)

// WorkplanInformer provides access to a shared informer and lister for
// Workplans.
type WorkplanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.WorkplanLister
}

type workplanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWorkplanInformer constructs a new informer for Workplan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWorkplanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWorkplanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWorkplanInformer constructs a new informer for Workplan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWorkplanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EngineV1alpha1().Workplans(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EngineV1alpha1().Workplans(namespace).Watch(options)
			},
		},
		&engine_v1alpha1.Workplan{},
		resyncPeriod,
		indexers,
	)
}

func (f *workplanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWorkplanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *workplanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&engine_v1alpha1.Workplan{}, f.defaultInformer)
}

func (f *workplanInformer) Lister() v1alpha1.WorkplanLister {
	return v1alpha1.NewWorkplanLister(f.Informer().GetIndexer())
}
