/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kube-ci/engine/apis/engine/v1alpha1"
	scheme "github.com/kube-ci/engine/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkplansGetter has a method to return a WorkplanInterface.
// A group's client should implement this interface.
type WorkplansGetter interface {
	Workplans(namespace string) WorkplanInterface
}

// WorkplanInterface has methods to work with Workplan resources.
type WorkplanInterface interface {
	Create(*v1alpha1.Workplan) (*v1alpha1.Workplan, error)
	Update(*v1alpha1.Workplan) (*v1alpha1.Workplan, error)
	UpdateStatus(*v1alpha1.Workplan) (*v1alpha1.Workplan, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Workplan, error)
	List(opts v1.ListOptions) (*v1alpha1.WorkplanList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Workplan, err error)
	WorkplanExpansion
}

// workplans implements WorkplanInterface
type workplans struct {
	client rest.Interface
	ns     string
}

// newWorkplans returns a Workplans
func newWorkplans(c *EngineV1alpha1Client, namespace string) *workplans {
	return &workplans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workplan, and returns the corresponding workplan object, and an error if there is any.
func (c *workplans) Get(name string, options v1.GetOptions) (result *v1alpha1.Workplan, err error) {
	result = &v1alpha1.Workplan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workplans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Workplans that match those selectors.
func (c *workplans) List(opts v1.ListOptions) (result *v1alpha1.WorkplanList, err error) {
	result = &v1alpha1.WorkplanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workplans.
func (c *workplans) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a workplan and creates it.  Returns the server's representation of the workplan, and an error, if there is any.
func (c *workplans) Create(workplan *v1alpha1.Workplan) (result *v1alpha1.Workplan, err error) {
	result = &v1alpha1.Workplan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workplans").
		Body(workplan).
		Do().
		Into(result)
	return
}

// Update takes the representation of a workplan and updates it. Returns the server's representation of the workplan, and an error, if there is any.
func (c *workplans) Update(workplan *v1alpha1.Workplan) (result *v1alpha1.Workplan, err error) {
	result = &v1alpha1.Workplan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workplans").
		Name(workplan.Name).
		Body(workplan).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *workplans) UpdateStatus(workplan *v1alpha1.Workplan) (result *v1alpha1.Workplan, err error) {
	result = &v1alpha1.Workplan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workplans").
		Name(workplan.Name).
		SubResource("status").
		Body(workplan).
		Do().
		Into(result)
	return
}

// Delete takes name of the workplan and deletes it. Returns an error if one occurs.
func (c *workplans) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workplans").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workplans) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workplans").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched workplan.
func (c *workplans) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Workplan, err error) {
	result = &v1alpha1.Workplan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workplans").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
