/*
Copyright 2018 The KubeCI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// FakeWorkplanLogs implements WorkplanLogInterface
type FakeWorkplanLogs struct {
	Fake *FakeExtensionsV1alpha1
	ns   string
}

var workplanlogsResource = schema.GroupVersionResource{Group: "extensions.kube.ci", Version: "v1alpha1", Resource: "workplanlogs"}

var workplanlogsKind = schema.GroupVersionKind{Group: "extensions.kube.ci", Version: "v1alpha1", Kind: "WorkplanLog"}
